#+TODO: TODO WAIT | DONE CANCEL
* Buyers
  https://gitlab.com/jesse23/buyer-what
#+BEGIN_SRC sh
  git -c http.sslVerify=false clone https://gitlab.com/jesse23/buyer-what ~/Project/buyer-what
#+END_SRC
** Home Test IP 
   http://192.168.1.114:8100
** Spint 2 - focus on purchase and ship page 
*** Design
**** Order Page
     1. Cost is not needed in this page.
     2. Name here is alias or wechat name.
**** Purchase Page
     1. Show/Modify cost attribute here.
     2. Group list by location for filtering.
**** Shipping Page
     1. Add shippment fee with a rough calculator, re-bundle helper.
     2. Shipment type like "IT", "Clothes", "Shoes"
     3. Contact sub page:
        1) Real name
        2) Phone
        3) Address
        4) National Identity Number
     4. Ship tracking number and shipping carrier.
     5. Add auto assign ID for tracing with package in delivery location.
     6. Group by Type, city, contact for filtering and re-bundle.
**** Acount Page
     1. Show/Modify cost attribute here
     2. Concurrency change practice in account:
        1) Original price in US Dollar.
        2) Shipment in CHN.
        3) Total in CHN.
        4) Better to have a preference to set it up.
*** Task list
**** TODO Extra feedback from sprint review, prioritize requirements
** Future
*** Get input from wechat and dealmoon
*** Sync data with csv on oneDrive
** Trouble shoot
*** You have not accepted the license… Android SDK Platform 26
#+BEGIN_SRC
Hi. Today I encountered this problem as well. However, changing the engine name to 6.2.3 was not enough for me. Nor was the solution suggested here: https://stackoverflow.com/questions/40383323/cant-accept-license-agreement-android-sdk-platform-2448.

What I did was download Android Studio. Then I updated the SDK version using the SDK manager provided by Android Studio (Tools/Android/SDK Manager). In the Android SDK Location click on the Edit button. There I was prompted with the option to update to API 27.

After updating, I created a new dummy android project (empty activity). After the project was created, the TODO console gave me the option to download the missing sdk components. There I was prompted with the ‘Accept licence’ popup. After accepting, I was able to build my ionic project without this error.
#+END_SRC
*** Android
   1. Install Android SDK
   2. Install SDK 24 and proper Image ( ATOM_x64 on windows )
   3. Set ANDROID_HOME correctly.
   4. ionic cordova emulate android
   5. ionic cordova run android --prod --release
